name: aur-sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  aur-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync AUR package with Github release
        uses: luisperezmarin/aur-sync-action@master
        with:
          package_name: typioca
          github_repo: 'bloznelis/typioca'
          github_local_repo: 'luisperezmarin/typioca_aur'
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          extra_dependencies: 'make'
